version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the project..."
      - ./gradlew clean build
      - ./gradlew generateYaml
  post_build:
    commands:
      - aws s3 rm s3://blue-eyed-soul-lambda-code-$STAGE/ --recursive
      - mkdir -p output
      - S3_KEY=$S3_KEY
      - GOOD_KEY=$(grep 'S3Key:' lambda.yml | awk '{print $2}')
      - STAGE=$STAGE
      - echo "Uploading ${GOOD_KEY} to S3..."
      - aws s3 cp build/distributions/blueeyedsoul.zip s3://blue-eyed-soul-lambda-code-$STAGE/$GOOD_KEY
      - echo "Packaging artifact..."
      - cp lambda.yml output/lambda.yml  # 👈 copy the infra template to output folder

artifacts:
  files:
    - lambda.yml
  base-directory: output
