version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the project..."
      - ./gradlew clean build
      - ./gradlew generateYaml
  post_build:
    commands:
      - echo "Clearing previous lambda*.zip files from S3..."
      - aws s3 ls s3://blue-eyed-soul-lambda-code/ | grep lambda- | awk '{print $4}' | while read key; do aws s3 rm s3://blue-eyed-soul-lambda-code/$key; done
      - mkdir -p output
      - S3_KEY=$S3_KEY
      - STAGE=$STAGE
      - echo "Uploading ${S3_KEY} to S3..."
      - aws s3 cp build/distributions/blueeyedsoul.zip s3://blue-eyed-soul-lambda-code-$STAGE/$S3_KEY
      - echo "Packaging artifact..."
      - cp lambda.yml output/lambda.yml  # 👈 copy the infra template to output folder
artifacts:
  files:
    - lambda.yml
  base-directory: output